### ISSUE TITLE
GaussianVariogram() undefined

### ISSUE THREAD

**Issue by kbojanek** [juliohm/GeoStats.jl#10]
Tests for package run successfully, but several functions appear to not be defined.

**Comment by juliohm** [comment]
@kbojanek, thank you for giving the package a try. Could you please share the code that is not working for you or the functions that are undefined?

I've just double checked and everything is working for me:

```julia
julia> using GeoStats
julia> GaussianVariogram()
GeoStats.GaussianVariogram{Float64}(1.0,1.0,0.0)
```

**Comment by kbojanek** [comment]
It must have been a problem on my end, I updated this morning and still had the issue. However after removing and reinstalling it appears to work fine.

Thank you for the great package.

**Comment by juliohm** [comment]
Thanks for giving feedback, good luck on your work.
