### ISSUE TITLE
GeoStats.examples() not working

### ISSUE THREAD

**Issue by Balinus** [juliohm/GeoStats.jl#11]
Hello, I tried the `GeoStats.examples()` command from the REPL and got the following error:

```julia
julia> GeoStats.examples()
ERROR: UndefVarError: examples not defined
```

```julia
julia> Pkg.status("GeoStats")
 - GeoStats                      0.3.5+             master
```

```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

edit - The function is perhaps not exported?

**Comment by juliohm** [comment]
Hi @Balinus, thank you for reporting the issue. I am not sure why the examples are not launching in your machine. Are you using the latest version of GeoStats.jl (master branch), correct? I think so given your status output. It is working for me here.

I expect it to be called like `GeoStats.examples()`, so it shouldn't be exported.

**Comment by Balinus** [comment]
It now works. I restarted Julia. Don't know why it works now as I already had GeoStats installed.

**Comment by juliohm** [comment]
Thanks, I am glad it is working :blush: I hope these examples will be useful to demonstrate the current features of the package and also to educate people about the existence of geostatistics. Please feel free to spread the words :+1: and report any other issue that you may have.
