### ISSUE TITLE
HaversineDistance raises DomainError

### ISSUE THREAD

**Issue by bask0** [juliohm/GeoStats.jl#14]
GeoStats v 0.4.3
Julia v 0.6.0

DomainError is raised for certain point pairs x, y passed to HaversineDistance.

Error happens here: `GeoStats/src/distances.jl:138`
More specific: `DomainError() in sqrt at base/math.jl:425`

```
136  # haversine formula
137  a = sin(Δφ/2)^2 + cos(φ₁)*cos(φ₂)*sin(Δλ/2)^2
138  c = 2atan2(√a, √(1-a))
```

a gets larger than 1 in some cases, which makes √(1-a) complain

a is very close to 1 (1.0000000000000002), I think it is a rounding error.

MWE:
```
using GeoStats
dist = HaversineDistance()
dist([1., -15.625], [-179, 15.625])
```

Some other point pairs that cause error (the pattern is obvious):
[7.125, -15.625]
[-172.875, 15.625]

[-62.375, -79.875]
[117.625, 79.875]

[-54.125, -82.875]
[125.875, 82.875]

[-124.375, -84.125]
[55.625, 84.125]

**Comment by juliohm** [comment]
Thank you @basilkraft for reporting the issue. Please let me know if you are aware of another equivalent formula for the distance that is less prone to floating point errors. I will try to find the time to research more about it.

As a side note, I am in the process of migrating all the distances in GeoStats.jl to Distances.jl. This means that you will be able to use any distance defined therein.

**Comment by basilkraft** [comment]
Thanks for the quick reaction @juliohm 

Just found this:

> Although this formula [haversine] is accurate for most distances on a sphere, it too suffers from **rounding errors** for the special (and somewhat unusual) case of **antipodal points** (on opposite ends of the sphere). A more complicated formula that is accurate for all distances is the following special case of the Vincenty formula for an ellipsoid with equal major and minor axes.
[Wikipedia: Great-circle_distance](https://en.wikipedia.org/wiki/Great-circle_distance)

Check the link, you will find the Vincenty formula, which is, as written there, more complicated. You will also find the spherical law of cosines, which is more simple but has a drawback:

> On computer systems with low floating-point precision, the spherical law of cosines formula can have large rounding errors if the distance is small (if the two points are a kilometer apart on the surface of the Earth, the cosine of the central angle comes out 0.99999999). For modern 64-bit floating-point numbers, the spherical law of cosines formula, given above, does not have serious rounding errors for distances larger than a few meters on the surface of the Earth.
[Wikipedia: Great-circle_distance](https://en.wikipedia.org/wiki/Great-circle_distance)

I found this nice explanation (for R)
[Great-circle distance calculations in R](https://www.r-bloggers.com/great-circle-distance-calculations-in-r/)

It seems that the Vincenty formula is an overkill.

Maybe just add this ;)
```
    # haversine formula
    a = sin(Δφ/2)^2 + cos(φ₁)*cos(φ₂)*sin(Δλ/2)^2
    a > 1. && (a = 1.) # <==========================
    c = 2atan2(√a, √(1-a))
```

**Comment by juliohm** [comment]
Thank you for the links, very useful information. Could you maybe share your use case so that I can have a better sense of how many users would be impacted by such change? Are you doing global estimation (and hence antipodal points)?

I am willing to implement the change you suggested, but I am just trying to assess how often it occurs in practice. I'd rather avoid introducing a branch in the code, specially if there is an alternative solution.

**Comment by bask0** [comment]
Everyone who works with global gridded data (e.g. satellite data) may be affected. A regular grid - besides some exotic case - will usually contain antipodal points.

**Comment by juliohm** [comment]
Thank you, I will investigate the issue a little further before patching the file. Perhaps there is a more accurate haversine implementation that we should use instead? Meanwhile, it is good to know that you can patch the code locally and proceed with your work.

**Comment by juliohm** [comment]
Thank you again for reporting the issue @bask0, I added a line for handling floating point errors. I will do the same with the implementation in Distances.jl
