### ISSUE TITLE
Covariance models not defined

### ISSUE THREAD

**Issue by masiddique** [juliohm/GeoStats.jl#2]
Hi,

I installed the package in Julia (`Pkg.add("GeoStats.jl`)
Later, `using GeoStats`

And then I was running the runtests.jl, where I encountered the problem:

> Covariance models: Error During Test
  Got an exception of type UndefVarError outside of a @test
  UndefVarError: GaussianCovariance not defined

It seems covmodels.jl is not automatically added with the package installation. I downloaded the file and ran it in the Julia terminal, and then the tests ran smoothly.

Shouldn't the definitions for covariance models be added in the package, for subsequent use in spatial predictions using kriging functions? 

Please excuse if this is a silly comment.

**Comment by juliohm** [comment]
Hi @masiddique, the tests are passing here, perhaps you are trying to run the `runtests.jl` scripts directly in the Julia prompt?

The way we test packages in Julia is by running:

```julia
Pkg.test("GeoStats")
```

Can you please confirm the issue is solved?

**Comment by masiddique** [comment]
Yes, I was running it at the prompt. Running `Pkg.test("GeoStats")` works fine, so my mistake.

However, I was wondering how to pass covariance models to `unikrig()` function since we don't have the functions to generate such models, like `GaussianCovariance()` or `SphericalCovariance()`?

**Comment by juliohm** [comment]
I will document it better, thank you for your feedback. See if the example below works for you:

```julia
using GeoStats

# create some data
dim = 3; nobs = 10
X = rand(dim, nobs); z = rand(nobs)
x₀ = rand(dim)

# define a covariance model
s, r = 1., 1. # sill and range
cov = GaussianCovariance(s,r)

# estimation
μ, σ² = kriging(x₀, X, z, cov=cov)
μ, σ² = unikrig(x₀, X, z, cov=cov)
```

**Comment by masiddique** [comment]
I get error:

> UndefVarError: GaussianCovariance not defined
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
 in (::Atom.##65#68)() at eval.jl:40
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:46
 in macro expansion at eval.jl:109 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60

**Comment by juliohm** [comment]
Thank you for catching this @masiddique, I had it fixed in the master branch but forgot to tag a new version of the package in the Julia ecosystem. I will be sending the new version for approval today, meanwhile you can get it working in the development branch by typing:

```julia
Pkg.checkout("GeoStats")
```

This will download the latest (unstable) version of `GeoStats`.

**Comment by masiddique** [comment]
Thank you @juliohm . The example given above works now.

**Comment by juliohm** [comment]
@masiddique you should now be able to use the stable version again:

```julia
Pkg.free("GeoStats")
```

The fix was merged. Thank you again.
