### ISSUE TITLE
Misleading plot in documentation

### ISSUE THREAD

**Issue by ziotom78** [juliohm/GeoStats.jl#21]
The plot shown in the [Quick Example](http://juliohm.github.io/GeoStats.jl/stable/#Quick-example-1) section of the documentation is misleading: if the user runs the code, it will not produce the same plot, as no Gaussian variogram is used. This should be explicitly stated in the documentation, or the plot changed.

**Comment by juliohm** [comment]
Good catch, I will update the plot and the code accordingly :+1:

**Comment by juliohm** [comment]
I've updated the plot everywhere, including docs, README.md and the paper.md file.

Thanks again for catching it.
