### ISSUE TITLE
Brainstorming ideas for project logo

### ISSUE THREAD

**Issue by juliohm** [juliohm/GeoStats.jl#23]
Thank you @cormullion for your incredible work. I am excited to try ideas for the logo and learn from you.

First, let me describe some of the visual elements in our current logo to give you some background in our research field. The logo shown below is made of a "scatter" of colored points in space representing measurements of a physical property at a few locations in a map. For example, a group of geologists doing field work can report rock properties at a few sites. We always attach to each measurement its coordinates in the map.

![geostats](https://user-images.githubusercontent.com/3345261/41202958-d00ad1c2-6c85-11e8-861c-71d3db8b68f9.png)

Given these scarce measurements, the job of geostatistics is to fill in the map by using the spatial correlation between the sampled locations. There are many methods for achieving this goal, each of them relying on some prior information.

The first classical approach is based on simple 2-point correlation as the prior. Instead of using correlation as a function of distance h, we use another related concept that is more general known as the variogram:

![variograms](https://user-images.githubusercontent.com/3345261/41203031-cc8e6508-6c86-11e8-97f7-cc21a4fb73f5.png)

which is basically "variogram(h) = 1 - correlation(h)". The variogram has a well-known symbol in the literature, it is denoted universally in textbooks with lowercase gamma: https://en.wikipedia.org/wiki/Gamma It may be useful as a visual reminder for practioners.

Another classical approach is based on training images. Instead of building a covariance model with the variogram function, we provide an image of reference that contains the patterns that we want to reproduce in the domain while filling the gaps. For many examples of such images, we have this repo: https://github.com/juliohm/GeoStatsImages.jl

In all geostatistical approaches, we can either estimate things locally or estimate the entire map globally. In the local approach, we usually define neighborhoods of points like the ellipsoid I drew in greyish color in the logo. The idea is that we fit a model only considering points inside of a neighborhood, and move this neighborhood around in order to fill the entire map.

I was thinking on a smaller, minimalist logo. Something that could reflect some of these visual elements I described above, and at the same time be easily remembered. Currently, the logo is too big making it impossible to fit in the documentation page tab in the top left. The Augmentor.jl package solved this logo size issue nicely by creating two variants of the logo, one of the top left tab, and a bigger one with the name written explicitly: https://evizero.github.io/Augmentor.jl/

I am open to any ideas, feel free to innovate = )

**Comment by cormullion** [comment]
I've jotted down a few ideas, some of these may catch your interest and can be iterated on. I'm not sure about some of them, but it's better to have something to start with...! :)

<img width="771" alt="screen shot 2018-06-10 at 22 59 04" src="https://user-images.githubusercontent.com/52289/41206797-148b48c8-6d02-11e8-8825-6c29d4e75264.png">

**Comment by juliohm** [comment]
They look great, I particularly like the top left option. =) Contours are everywhere in geostatistical workflows. I am sharing more pictures of the complexity of shapes and patterns that we see in nature so that you get some more inspiration:

- The [Ganges delta](https://www.google.com/search?biw=1600&bih=807&tbm=isch&sa=1&ei=8KIdW5zrHN-x0PEPhYWR0AM&q=ganges+delta&oq=ganges+delta&gs_l=img.3..35i39k1j0i19k1l9.8732.10002.0.10171.12.12.0.0.0.0.163.1310.5j7.12.0....0...1c.1.64.img..0.12.1306...0j0i67k1j0i10k1.0.F8wr-b6JSjk) is beautiful, it is the type of complexity that we are trying to capture with these methods (channelized systems, fractals, river-like morphology). It is a multi-scale problem.

If there was a way that we could combine some of the complex forms of the Ganges delta or maybe represent them with contours in a cartoon-like logo, that would be awesome. Also, if we could emphasize the "stats" part of the "geostats", that would be :+1:  It is really about performing statistics in the context of spatial data. The "geo" is there for historical reasons, we could apply all these methods to other planets and abstract spaces that are not planets as well =)

**Comment by juliohm** [comment]
Australia also has some beautiful patterns from satellite:

![screenshot from 2018-06-10 16-27-05](https://user-images.githubusercontent.com/3345261/41207463-3a74fcf0-6ccb-11e8-80ad-17db656d6824.png)

Food for thought.

**Comment by cormullion** [comment]
playing with a stylized color-based view of the delta, trying to keep it very simple is tricky!

<img width="342" alt="screen shot 2018-06-11 at 13 24 07" src="https://user-images.githubusercontent.com/52289/41231385-d6b0de18-6d7a-11e8-90a4-a321b2c7f3c2.png">

**Comment by cormullion** [comment]
I started liking these sinuous curves with data points, but I'm heading off into Legend of Zelda territory a bit too much now ?!  :)

<img width="350" alt="screen shot 2018-06-11 at 15 17 09" src="https://user-images.githubusercontent.com/52289/41237088-97c533b0-6d8a-11e8-900b-4ea212b8fa17.png">

**Comment by juliohm** [comment]
These are starting to look awesome! I like the colors of the first one, reminds Earth, terrain and water. Any way to break the symmetry? and maybe place the source of the sinusoidal curves in the top left? The image below for example represents a deltaic system again where the channels are emerging from the top left corner:

![screenshot from 2018-06-11 08-07-27](https://user-images.githubusercontent.com/3345261/41240191-ca4b95a4-6d4e-11e8-84a0-ddffb6219f01.png)

Another view (or realization):

![screenshot from 2018-06-11 08-07-45](https://user-images.githubusercontent.com/3345261/41240221-d6a1701c-6d4e-11e8-969a-a902009025e8.png)

And an illustration of how the scanning algorithm goes on finding the patterns with moving windows of small size:

![screenshot from 2018-06-11 08-06-10](https://user-images.githubusercontent.com/3345261/41240390-3d8e6bfe-6d4f-11e8-8f1c-91b2655c3a8b.png)

If we could combine the Earth colors of the first logo with the channels of the second, that would be so cool. Below is more food for thought, 3D models are also common, not only 2D:

![screenshot from 2018-06-11 08-05-40](https://user-images.githubusercontent.com/3345261/41240333-1f91ed4c-6d4f-11e8-8666-cecd32f3a68b.png)

**Comment by juliohm** [comment]
Had an even nicer idea, what about embedding the name GeoStats.jl inside of
a more complex pattern? For example, make the S in GeoStats.jl one of these
sinusoidal channels, extend some of the letters with more artistic shapes?
In that case I think even if we stick with black color it will look great.
If you have suggestions for colors in the name, feel free to play with them
:) I like the idea of retaining the name in the logo, creates a strong
identity.

**Comment by cormullion** [comment]
This is getting too complicated in my view... Logos can't illustrate everything that's provided, they have to concentrate on suggesting the right feelings... Sometimes you have to take things away to improve the result (“I have only made this letter longer because I have not had the time to make it shorter." - Pascal)

A good question is: does it work at 64 by 64 pixels square?

<img width="684" alt="screen shot 2018-06-11 at 18 21 57" src="https://user-images.githubusercontent.com/52289/41246939-6b4f54ea-6da4-11e8-9ee9-02eeb67ca4cf.png">

**Comment by cormullion** [comment]
This is only slightly better... 

Back to the drawing board later this week... :)

<img width="683" alt="screen shot 2018-06-11 at 19 44 46" src="https://user-images.githubusercontent.com/52289/41250831-f9700034-6daf-11e8-8e87-1156ab379d23.png">

**Comment by juliohm** [comment]
Fully agree, I love the idea of keeping it simple. =) All of them are looking so beautiful anyways! I am sympathetic with the last idea of having the name GeoStats.jl becoming part of a more complex pattern. Something like the terrible draft I just made here:

![20180611_114531](https://user-images.githubusercontent.com/3345261/41251112-cfeff256-6d6d-11e8-989b-1a38c2b100c5.jpg)

You see how my artistic skills are like a disaster hahaha. I LOVED the last one with the grid in the back. Maybe combine the grid in the background with something like the drawing above with some channels and ellipses and we can call it done :heart:

**Comment by cormullion** [comment]
Well, I tried make the "S" run through the image, but I didn't like the results, and the image kept on saying "TATS" to me (which definitely isn't what you want, at least in the UK)!

So I've ended up with this more restrained design, which I think is more effective at smaller sizes than the others... It could be simplified even more in other use cases.

<img width="675" alt="screen shot 2018-06-13 at 13 08 52" src="https://user-images.githubusercontent.com/52289/41350424-0436d7ac-6f0b-11e8-9138-c5f64014ef50.png">

**Comment by juliohm** [comment]
I liked it, it is elegant. The contours in the background are great. Maybe
we don't need the channel in the center on this one, or perhaps we could
maintain the channel but lower its frequency of oscillation? I like the
colors already, but if you have other color combinations that you like,
would be happy to check :)

The idea with the grids didn't look promising?

**Comment by cormullion** [comment]
I use the colorschemes from [ColorSchemes.jl](http://juliagraphics.github.io/ColorSchemes.jl/latest/basics.html) to explore color combinations so it's easy to cycle through them. With over 300, there are plenty of possibilities for choosing 2. But it's always harder to make a decision than to explore alternatives... :)

![julia-geostats-10](https://user-images.githubusercontent.com/52289/41368300-79432bb2-6f39-11e8-85b4-212514977443.png)

**Comment by juliohm** [comment]
So beautiful! Liked the second one (first row, second column), I will add it to the documentation on the top left so that everyone can see it! :+1:  Any way that I could credit you for your work? For sure I am adding an acknowledgements section in the documentation, just wondering if you have a link or website that I could promote?

**Comment by juliohm** [comment]
If you could export the various color combinations, that would be helpful to decide later. They all look great :)

**Comment by juliohm** [comment]
Also, do you think that it would be interesting to have a different ratio for the logo like 4x3 instead of the square 4x4? Something that would read more horizontally with "geo" and "stats" closer together. Just wondering how it would look like.

**Comment by juliohm** [comment]
If you could add the ".JL"` in the "STATS" somewhere after the ratio 4x3, it would be :ok_hand:

**Comment by cormullion** [comment]
After some experiments I decided that I prefer text to be done this way.

<img width="229" alt="screen shot 2018-06-15 at 12 31 25" src="https://user-images.githubusercontent.com/52289/41465954-11c52552-7098-11e8-95d2-78ef9a6fa557.png">

I quite like this — it may be colourful, but it works well at smaller sizes...

**Comment by juliohm** [comment]
I like the contours in the bottom part, very nice shapes and colors. I have yet another idea that I think would be interesting. I really like the gridded patterns you created in one of the previous iterations:

![screenshot from 2018-06-15 12-34-26](https://user-images.githubusercontent.com/3345261/41486221-8d63aeea-7098-11e8-8147-94427da9a108.png)

Do you think you could embed the name `GeoStats.jl` in a grid-like format like that? Something like putting GeoStats.jl in white color in the backgroung and have the grid opacity change in a few cells so that only pieces of the letters appear? The opacity could also be applied to a map that shows complex contours like the last one, what do you think?

**Comment by cormullion** [comment]
I'll have a look next week! :)

**Comment by juliohm** [comment]
Thanks, have a great weekend! :)

**Comment by cormullion** [comment]
Here's your tile effect — its quite nice, but reduces the readability/recognizability of course, at small sizes.

<img width="514" alt="screen shot 2018-06-18 at 09 00 02" src="https://user-images.githubusercontent.com/52289/41524637-16692d70-72d6-11e8-87a0-8625d3d31dcd.png">

here compared with the previous iteration:

<img width="452" alt="screen shot 2018-06-18 at 08 59 20" src="https://user-images.githubusercontent.com/52289/41524574-e94bfe58-72d5-11e8-8912-1e0f707fed72.png">

For non-icon uses, I think you'd be better with text, using the background texture for plots or whatever:

<img width="631" alt="screen shot 2018-06-18 at 09 01 09" src="https://user-images.githubusercontent.com/52289/41524742-5b2b8a8e-72d6-11e8-8c0a-79afcd18fd8d.png">

I'm still thinking there's a bit too much visual complexity here, but you seem to like it, so...😂😅 :)

**Comment by cormullion** [comment]
No worries. I'm mostly out of time on this one anyway. But it was fun. :)

**Comment by juliohm** [comment]
Thank you @cormullion , I really appreciate your work. I will familiarize myself with the options and decide later what would be a good choice. I am impressed by your agility to create them :)

**Comment by juliohm** [comment]
Thank you again for playing with the concepts, it was a lot of fun :) I am closing the issue for now.
