### ISSUE TITLE
Cannot display empirical variogram correctly

### ISSUE THREAD

**Issue by tianzeliu** [juliohm/GeoStats.jl#28]
When I tried to generate an empirical variogram and plot it using the same command as in the example, an error message was given:

`'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
WARNING: Base.γ is deprecated, use MathConstants.γ instead.
  likely near /Users/tianze/.julia/packages/IJulia/DL02A/src/kernel.jl:41` 

and the figure shown (see attached figure) is always the same no matter what nlags I choose. I am using Julia 0.7.0 and the version of Jupyter is 4.4.0. Thanks a lot!

![screen shot 2018-11-14 at 9 36 19 pm](https://user-images.githubusercontent.com/23426043/48532468-59b99980-e855-11e8-9e03-92dd29e431b4.png)

**Comment by juliohm** [comment]
Hi @tianzeliu , thank you for reaching out. Could you please provide a minimum example reproducing the issue?

**Comment by tianzeliu** [comment]
Hi Julio,
I am sorry that I discovered what was wrong right after I opened the issue. It was actually a problem with the input format of `EmpiricalVariogram`. I thought it requires the two coordinates in two column vectors, but it actually requires two row vectors. After fixing it the figure turns out normal. 
However, there is yet another issues with `@manipulate`, though I know that it is more proper to rise the issue in `Interact.jl`. When I tried to manipulate the figure in Jupyter notebook, I always receive the error message `WebIO not detected`. Here are the package I was using:
`Pkg.add("LaTeXStrings")
Pkg.add("PyCall")
Pkg.add(["GeoStats","Plots","PyPlot"])
Pkg.add("Interact")
Pkg.add("WebIO")
Pkg.add("IJulia")
Pkg.add("Distances")

using IJulia
using Pkg, Random
using Plots
using Interact
using WebIO
using Distances`

The version of Jupyter is 4.4.0 and the version of Julia is 0.7.0. Is it possible for you to provide some insight on this? Thank you very much for your swift response!

Tianze

**Comment by juliohm** [comment]
Thank you @tianzeliu for updating the issue. I agree the best place to ask about the errors you are having is in Interact.jl. I remember it was causing some errors for me as well in the transition to Julia 0.7. I think they should have solved all the issues by now, but please ask there for directions.

I am closing this one for now. Best.
