### ISSUE TITLE
Nugget variances

### ISSUE THREAD

**Issue by masiddique** [juliohm/GeoStats.jl#4]
Hi

At the moment, the covariance models do not allow nugget variances. Since it is an often desired feature, I think it should be added. @juliohm : If you agree to it, please check my pull request for an example addition of nugget field in the GaussianCovariance composite type definition. Thanks.

**Comment by juliohm** [comment]
Thank you @masiddique , I merged the PR https://github.com/juliohm/GeoStats.jl/pull/5, I appreciate it.

Feel free to add nugget to the other models too, I will merge them :+1:

**Comment by juliohm** [comment]
I will just reorder the nugget to be the last field instead of the first and stop to think about the total sill vs. partial sill issue.

**Comment by juliohm** [comment]
Fixed on the master branch, thanks again for catching this.
