### ISSUE TITLE
Normal score transform

### ISSUE THREAD

**Issue by lperozzi** [juliohm/GeoStats.jl#44]
To transform the dataset in a Gaussian space,  we can define an empirical distribution

`d = EmpiricalDistribution(values)` and then transform to Gaussian with `transform!(values, d, Normal(0,1))`

It is possible to pass a column of a DataFrame instead of an Array  as `values`?

**Comment by juliohm** [comment]
Thank you for opening the issue. It should be easy to refactor the `EmpiricalDistribution` constructor to accept any `AbstractVector`, including a `DataFrame` column. If you feel like submitting a PR, I'd be happy to review and merge. Otherwise, I will tackle the issue when time allows.

**Comment by juliohm** [comment]
@lperozzi could you please share the code you tried to use? If you have a DataFrame object `df`, you can do `df.a` to access the column `a` as a vector. It is working here for me.

**Comment by lperozzi** [comment]
@juliohm you're right! It works for me too. I should have made a syntax error. Sorry for that

**Comment by juliohm** [comment]
No problem at all. I will close the issue for now. Let me know if something else is not working. Thanks for opening the issue.
